services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_HOST
        value: n8n.onrender.com
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n.onrender.com/
      # n8n credential (login for owner account)
      - key: N8N_USER_EMAIL
        value: dushyant5er@gmail.com
      - key: 
        value: Kashi@1608
      # LinkedIn automation credentials
      - key: LINKEDIN_EMAIL
        sync: false
      - key: LINKEDIN_PASSWORD
        sync: false
      # Security and permissions for n8n Code node
      - key: N8N_BLOCK_ENV_ACCESS_IN_NODE
        value: "false"           # Allow env vars for Code, as required by LinkedIn login
      - key: N8N_BLOCK_FILE_ACCESS_TO_N8N_FILES
        value: "true"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"            # Enhances security for config/settings file
      - key: N8N_SAMESITE_COOKIE
        value: lax
      - key: N8N_SECURE_COOKIE
        value: "true"
          # For SQLite connection pool (must be > 0 for future n8n compatibility)
      - key: DB_SQLITE_POOL_SIZE
        value: "2"            # Or any value > 0

    # For enabling task runners (will soon be required in all n8n)
      - key: N8N_RUNNERS_ENABLED
        value: "true"

    # For Code node/env access inside n8n (needed for your LinkedIn env usage!)
      - key: N8N_BLOCK_ENV_ACCESS_IN_NODE
        value: "false"
