services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_HOST
        value: n8n.onrender.com
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n.onrender.com/
      # n8n credential (login for owner account)
      - key: N8N_USER_EMAIL
        value: dushyant5er@gmail.com
      - key: 
        value: Kashi@1608
      # LinkedIn automation credentials
      - key: LINKEDIN_EMAIL
        sync: false
      - key: LINKEDIN_PASSWORD
        sync: false
    # Security and session options for n8n
      - key: N8N_SECURE_COOKIE
        value: "true"                    # Ensure cookies are sent only over HTTPS
      - key: N8N_SAMESITE_COOKIE
        value: lax                       # Cookies sent with top-level navigation (default: lax)
      - key: N8N_BLOCK_FILE_ACCESS_TO_N8N_FILES
        value: "true"                    # Block access to .n8n/config files for security
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"                    # Restrict config/settings file permissions

# Access controls for Node/code execution
      - key: N8N_BLOCK_ENV_ACCESS_IN_NODE
        value: "false"                   # Allow env variables in Code node (needed for LinkedIn)

# Internal database and future n8n runtime requirements
      - key: DB_SQLITE_POOL_SIZE
        value: "2"                       # Use a pool for SQLite connections (any value > 0)
      - key: N8N_RUNNERS_ENABLED
        value: "true"                    # Enable n8n task runners (future default)
