services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_HOST
        value: n8n.onrender.com   # Update after first deploy with your real Render domain
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n.onrender.com/
      # These will be set manually in Render Dashboard (not stored in repo)
      - key: LINKEDIN_EMAIL
        sync: false
      - key: LINKEDIN_PASSWORD
        sync: false
